theme: jekyll-theme-minimal
title: [Discrination Measures]
description: [A Benchmarking Platform for Discrimination Discovery in Machine Learning]
show_downloads: ["false"]
# google_analytics: [Your Google Analytics tracking ID]