theme: jekyll-theme-minimal
title: [Discrimination Measures]
description: [A Benchmarking Platform for Discrimination Discovery in Machine Learning]
show_downloads: ["false"]
google_analytics: [UA-101054904-1]